#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# set layout to be tiled (default: float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# set all padding and gaps to 10pt (default: 0)
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# focus the window under the cursor when it moves (default: off)
yabai -m config focus_follows_mouse autofocus

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# disable tiling for following apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^IINA$"            manage=off
yabai -m rule --add app="^PicView$"         manage=off
yabai -m rule --add app="^System Information$"  manage=off
yabai -m rule --add app="^Finder$" title="(Copy|Move|Info|Preferences)" manage=off
yabai -m rule --add app="^Calculator$"          manage=off
yabai -m rule --add app="^Archive Utility$"     manage=off
yabai -m rule --add app="^App Store$"           manage=off
yabai -m rule --add app="^1Password$"           manage=off
yabai -m rule --add app="^Raycast$"             manage=off

echo "yabai configuration loaded.."
